name: ci-cd 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v4
    - name: docker-build
      run: docker build . --tag minecraft-server
